version: '3.8'

services:
    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        environment:
            SA_PASSWORD: ${DatabasePassword}
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        volumes:
            - db_data:/var/opt/mssql
        networks:
            - app_network

    webapi:
        depends_on:
            - db
        networks:
            - app_network
  
    react_frontend:
        depends_on:
            - webapi
        ports:
            - "53122:80"
        networks:
            - app_network

    angular_frontend:
        depends_on:
            - webapi
        ports:
            - "63217:80"
        networks:
            - app_network

    nginx_proxy:
        build:
            context: ./nginx-proxy
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app_network
        depends_on:
            - react_frontend
            - angular_frontend

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
